(function() {
  moment.tz.link('Australia/Brisbane|Brisbane');
  //API key generated on 21/10/16
  var OPENWEATHER_VERIFY_KEY = '6770161bf784f5d87403b211af6b3a69';

  //Future task... work on weather first
  //var NEWS_API_KEY = '88b131d2cdca1ec5b3c7ebf4f11cc6169cf632b5';

  function renderableTitle(title) {
    if(title.length <= 50) {
      return title;
    }
    return title.slice(0, 36) + '...';
  }

  //Global Variables
  return {
    events: {
      'app.activated':'onActivated',
      'fetchRequester.done':'onFetchRequester',
      'fetchLocation.done': 'onFetchLocation',
      'fetchWeather.done': 'onFetchWeather',
      //'fetchNews.done': 'onFetchNews'
    },

    requests: {
      fetchRequester: function() {
        return {
          url: '/api/v2/users/' + this.idx + '.json',
          type: 'GET',
          dataType: 'json'
        };
      },

      fetchLocation: function(number) {
        return {
          url: 'http://apilayer.net/api/validate?access_key=' + NUM_VERIFY_KEY + '&number=' + number,
          type: 'GET',
          dataType: 'json'
        };
      },

      fetchWeather: function(query) {
        return {
          url: 'http://api.openweathermap.org/data/2.5/weather?q=' + query + '&appid=' + OPENWEATHER_VERIFY_KEY,
          type: 'GET',
          dataType: 'JSON'
        };
      },

      onActivated: function() {
            this.idx = this.ticket().requester().id();
            this.switchTo('loading');
            this.ajax('fetchRequester');
          },

          onFetchLocation: function(data) {
            // var mockedResponseWithLocation = {"valid":true,"number":"61383721203","local_format":"0383721203","international_format":"+61383721203","country_prefix":"+61","country_code":"AU","country_name":"Australia","location":"Melbourne","carrier":"","line_type":"landline"}
            // var mockedResponse = {"valid":true,"number":"61406699159","local_format":"0406699159","international_format":"+61406699159","country_prefix":"+61","country_code":"AU","country_name":"Australia","location":"","carrier":"Vodafone Hutchison Australia Pty Ltd (VHA)","line_type":"mobile"}
            var locationData = data;
            // var locationData = mockedResponseWithLocation;
            this.country = locationData.country_name;
            if(typeof(locationData.location) !== 'undefined') {
              this.location = locationData.location === "" ? locationData.country_name : locationData.location + ", " + locationData.country_code;
            } else {
              this.location = 'Unknown';
            }

            this.weatherQuery = locationData.location === "" ? locationData.country_code : locationData.location + "," + locationData.country_code;
            this.ajax('fetchWeather', this.weatherQuery);
          },

          render: function() {
            this.switchTo('main',{
              weatherIcon: this.weatherIcon,
              location: this.location || 'Unknown',
              callTime: this.callTime,
            //  news: this.news
            });
          },

          onFetchRequester: function(data) {
            console.log(data.user.phone);
            var timezoneMoment = moment(this.ticket().createdAt()).tz(data.user.time_zone);
            this.callTime = timezoneMoment.format('YYYY-MM-DD hh:mm a');
            var hour = timezoneMoment.get('hour');
            this.nightTime = hour > 20 && hour < 6;
            this.ajax('fetchLocation', data.user.phone);
          },

          onFetchWeather: function(data) {
            this.weatherIcon = 'sunny.png';
            if(data.weather[0].main === "Clear") {
              this.weatherIcon = this.nightTime ? "night.png" : "sunny.png";
            } else {
              this.weatherIcon = this.nightTime ? "night-rain.png" : "day-rain.png";
            }

            //this.ajax('fetchNews', this.country);
          },

          //onFetchNews: function(data) {
            //this is the mocked data in case api limit is reached
            // var data = {
            //   "status": "OK",
            //   "usage": "By accessing AlchemyAPI or using information generated by AlchemyAPI, you are agreeing to be bound by the AlchemyAPI Terms of Use: http://www.alchemyapi.com/company/terms.html",
            //   "totalTransactions": "30",
            //   "result": {
            //     "docs": [
            //       {
            //         "id": "MTE0ODg2MTY3OTF8MTQ2MzU0NjM0Mg",
            //         "source": {
            //           "enriched": {
            //             "url": {
            //               "title": "Man battles crocs in Australia with spanner, spark plugs",
            //               "url": "http://news.abs-cbn.com/lifestyle/classified-odd/05/18/16/man-battles-crocs-in-australia-with-spanner-spark-plugs"
            //             }
            //           }
            //         },
            //         "timestamp": 1463546342
            //       },
            //
            //       {
            //         "id": "MTE0ODYxNTE1MjF8MTQ2MzU0NjA0Mg",
            //         "source": {
            //           "enriched": {
            //             "url": {
            //               "title": "AUSTRALIA/NEW ZEALAND DAYBOOK: RBA Policy Statement",
            //               "url": "http://www.bloomberg.com/news/articles/2010-11-04/australia-new-zealand-daybook-telecom-n-z-earnings-myer-briefing"
            //             }
            //           }
            //         },
            //         "timestamp": 1463546042
            //       },
            //       {
            //         "id": "MTE0ODEzNjI4NTR8MTQ2MzU0NTU0MA",
            //         "source": {
            //           "enriched": {
            //             "url": {
            //               "title": "Apple: Ask record labels, movie studios why iTunes pricing is higher in Australia | ZDNet",
            //               "url": "http://www.zdnet.com/article/apple-ask-record-labels-movie-studios-why-itunes-pricing-is-higher-in-australia/"
            //             }
            //           }
            //         },
            //         "timestamp": 1463545540
            //       }
            //     ],
            //     "next": "NDYwMDg4MzU3Mzc0NjM4NTI2OXxNVEUwT0RFek5qSTROVFI4TVRRMk16VTBOVFUwTUF8MTIxOTIzNjIyMjA0NjkzNjE0Mjl8fDE1MzQ5MTExNTIyNjkwMjQyODUyfHwxNjEyNTc1ODQ5Mjg4MzYxNTY2M3w",
            //     "status": "OK"
            //   }
            // };
          //  if(data.result && data.result.docs) {
          //    console.log(data.result.docs);
          //    this.news = data.result.docs.map(function (elem) {
          //      return {
          //        title: elem.source.enriched.url.title,
          //        link: elem.source.enriched.url.url,
          //        renderable_title: renderableTitle(elem.source.enriched.url.title)
          //      };
          //    });
          //  } else {
          //    this.news = []
          //  }
          //  console.log(this.news);
          //  this.render();
          }
        };
      }());
